"""Late initial migration

Revision ID: 407ee03fde50
Revises: 
Create Date: 2021-03-20 17:42:31.834353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407ee03fde50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_comment_timestamp', table_name='user_comment')
    op.drop_table('user_comment')
    op.drop_index('ix_anonymous_comment_timestamp', table_name='anonymous_comment')
    op.drop_table('anonymous_comment')
    op.alter_column('comment', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_table('anonymous_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anonymous_comment_timestamp', 'anonymous_comment', ['timestamp'], unique=False)
    op.create_table('user_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_comment_timestamp', 'user_comment', ['timestamp'], unique=False)
    # ### end Alembic commands ###
